name: Analyze

on: [push, pull_request]

jobs:
  decomplint:
    name: ${{ matrix.target }} annotations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - LEGORACERS
          - GOLDP
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install python libraries
      run: |
        pip install -r tools/requirements.txt

    - name: Run decomplint
      run: |
        reccmp-decomplint ${{ matrix.target }} --module ${{ matrix.target }} --warnfail
